version: "3.8"
name: mailserver
services:
  app:
    image: tiredofit/nginx-php-fpm:8.1-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example.rule=Host(`mailserver.localhost`)"
      - "traefik.http.routers.example.entrypoints=web"
    working_dir: /www/html
    volumes:
      - ./:/www/html
    networks:
      - gateway

networks:
  gateway:
    name: gateway
    external: true